name: Unit Tests

on: [ push, pull_request ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite: [ neodisambiguate ]
        java-version: [ 1.8, 11, 17, 21 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Cache for Scala Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.mill/download
            ~/.m2/repository
            ~/.cache/coursier
          key: ${{ runner.os }}-java-mill-${{ matrix.java-version }}-${{ hashFiles('**/build.sc') }}
          restore-keys: ${{ runner.os }}-java-mill-
      - name: Compile Scala Code
        run: |
          ./mill --no-server clean
          ./mill --no-server --disable-ticker ${{ matrix.suite }}.compile
      - name: Test Scala Code
        run: |
          ./mill --no-server --disable-ticker ${{ matrix.suite }}.test
      - name: Create Code Coverage Report
        if: matrix.java-version == '11'
        run: |
          ./mill --no-server --disable-ticker ${{ matrix.suite }}.scoverage.xmlReport
      # TODO: build an HTML report and upload as an artifact
